name: Upload GH Release

on:
  workflow_call:  
    secrets:
      GH_PAT:
        required: true
jobs:  
  upload-to-github-release:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Configure Git
        run: |
          git config --global user.email "jonperez102@gmail.com"
          git config --global user.name "jon-perez18"
      
      - name: Create and push tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git fetch --tags
          latest_tag=$(git tag --list 'v*' | sort -V | tail -n 1)
      
          if [[ -z "$latest_tag" ]]; then
            new_tag="v0.0.1"
          else
            IFS='.' read -r major minor patch <<< "${latest_tag#v}"
            patch=$((patch + 1))
            new_tag="v${major}.${minor}.${patch}"
          fi
      
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
      
          git tag $new_tag
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin $new_tag



      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: build-artifact
          path: ./artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: "Release ${{ env.NEW_TAG }}"
          files: ./artifact/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
